### PR TITLE
Added favicon (just solid #840000)

### PR DESCRIPTION
**Pull request by eddotman**
I know it's kind of a silly addition, but it drives me nuts to have a link w/o a favicon on my bookmarks bar...

### CODE REVIEW

**Comment by karpathy** [comment]
haha that's fair. Not a huge fan of the specific favicon myself, but I'll design one and make the change when I can spare some time :) thanks!

**Comment by eddotman** [comment]
Awesome, thanks! I'll leave this open for now and kill the pull request whenever the favicon is up. I might also try a design that ties in better w/ the arxiv favicon instead of just being a plain color block... I'll add that here if/when I get around to making a non-ugly version of that.

**Comment by karpathy** [comment]
I think I'd just want it to be a simple white "AS" on top of the arxiv-sanity-red-color. If you make the change I'd be happy to merge it. You might also want to include the favicon html into the other .html file for discussions.

**Comment by eddotman** [comment]
Added image and thanks for the catch on the other html file.

I left the font as (bold) arial to match the header on the website. I didn't actually test this (i.e., I haven't run my own instance of the site), but since it's just a favicon link, I imagine that everything should work...

**Comment by karpathy** [comment]
cool! ty :)

**Pull request merged**
