### PR TITLE
Add arXiv vanity links to the papers

### PR DESCRIPTION
**Pull request by jasikpark**
This should add links to the arXiv vanity page for the papers http://arxiv-vanity.com

It's the one thing that I've been still hoping for from arXiv-sanity.com

### CODE REVIEW

**Comment by jasikpark** [comment]
When I first wrote this, arxiv-vanity was still error-prone, though it generally worked. Now it's the opposite. Most arxiv articles render correctly through it.

**Comment by bfirsh** [comment]
@jasikpark Arxiv Vanity maker here! Thanks for this, it looks great.

A usability suggestion: the link should probably be “HTML” or “Web” for those who don’t know what Arxiv Vanity is. It could perhaps have a title attribute of “on Arxiv Vanity” to make it clear what is going to happen when you hover over it. Or, if there is space, the text could just be “HTML on Arxiv Vanity”.

**Review by jasikpark — COMMENTED** [review]
This would make the ave of the link to arxiv-vanity for the paper a bit more understandable to users who have never used arxiv-vanity

**Comment by jasikpark** [comment]
@bfirsh is there anything else I can do to make it simple to answer whether this could be merged?

**Comment by bfirsh** [comment]
This looks good to me!

**Comment by bfirsh** [comment]
@karpathy What do you think? We get lots of requests for this from arXiv Vanity users. An email today reminded me of this issue...

**Comment by jasikpark** [comment]
arxiv vanity is still going strong, idk about this project tho - good luck and thanks for building a good tool!

**Pull request closed without merging**
